name=input("what is your name")
print("hello", name)
age=input("what is your age")
print("i am a simple calculator. I can simply add, subtract,multiply and divide")
a=float(input("enter your 1st number"))
b= float(input("your second number"))
sum=float(a+b)
print("addition",sum)
product=float(a*b)
print("product" ,product)
division= float(a/b)
print("a/b",division)
vice_versa=float(b/a)
print("b/a", vice_versa)
subtract=float(a-b)
print("a-b", subtract)
rev_subtract=(b-a)
print("b-a", rev_subtract)

